### ISSUE TITLE
Rawhide tests failing on production autocloud

### ISSUE THREAD

**Issue by AdamWill** [kushaldas/tunir#41] opened 2016-04-12 22:26 UTC
Rawhide tests are failing on production autocloud, e.g.:

https://apps.fedoraproject.org/autocloud/jobs/1932/output
https://apps.fedoraproject.org/autocloud/jobs/1930/output

I don't know what's going on with the Vagrant tests, but I can see the problem with the Cloud base qcow2 test (1930). Production autocloud seems to be using an older tunir (0.12). In that version of tunir, `testvm.py` calls `virt-builder --get-kernel` and then does a couple of globs to extract a kernel and initramfs from the image under test. It assumes it will get a `vmlinuz*` and a `initramfs*`, but in fact with the current Rawhide Cloud_base image there is no `initramfs` file. virt-builder only extracts an `initrd-plymouth.img`, which I don't think is a real initramfs. What I'm guessing has happened is the Cloud images have been streamlined to run without an initramfs, so tunir 0.12's assumption that it will get one from the image is no longer valid.

The code has completely changed in current git master tunir, so I don't know if this issue is resolved or if it's still lurking elsewhere. But that code isn't in production.

**Comment by kushaldas** [comment] 2016-04-13 06:59
The newer version of Tunir will go live along with the change in autocloud. The current failures are due to missing initramfs due to failure in mkinitrd.
More details in this [thread](https://lists.fedoraproject.org/archives/list/rel-eng@lists.fedoraproject.org/thread/235SJFDTUXFKPD36CBYGCAOROK2K3KVW/).

Closing this as not a bug for Tunir.

**Closed as completed by kushaldas** 2016-04-13 06:59 UTC
